version: 2
updates:
  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: weekly
    cooldown: # applies only to version-updates (security-updates will be suggested immediately)
      default-days: 10
      semver-minor-days: 14 # wait 14 days before applying minor updates
      semver-major-days: 28
